### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by EmreOzkose** [sming256/AdaTAD#1]
Hi, congratulations on the great work! When will you plan to share the code?

**Comment by sming256** [comment]
Thanks for your interest! We plan to release the code, pretrained checkpoint, and demo in the next month.

**Comment by andypinxinliu** [comment]
Hi, is there any update for the code release

**Comment by zhangwen666666** [comment]
Hi, congratulations on the great work! When will you plan to share the code?

**Comment by LIUQI-creat** [comment]
Hi, thanks for your great work! When will you plan to release the code?

**Comment by sming256** [comment]
Thanks for your interest! We will release the code within this month, as well as a TAD codebase supporting more methods. @andypinxinliu @zhangwen666666 @LIUQI-creat

**Comment by andypinxinliu** [comment]
Hi, AdaTAD is really a great and impressive work that makes end2end achievable without preprocessing! When will you plan to release the code?

**Comment by sming256** [comment]
We are finalizing the code and the pretrained model. Should be released soon. In the meantime, you can explore our newly released TAD codebase. https://github.com/sming256/opentad

**Comment by sming256** [comment]
Dear all, AdaTAD is released at [OpenTAD](https://github.com/sming256/OpenTAD/tree/main/configs/adatad)! We achieve an average mAP of 42.90% on ActivityNet and 77.07% on THUMOS14. Please have a check!
